export const labelMap = {
    titre: 'Titre Banner',
    subtitle: 'Description Banner',
    video: 'Vidéo',
    image: 'Image',
    collapse1img : 'Image bloc 1',
    collapse1text: 'Titre bloc 1',
    collapse2img: 'Image bloc 2',
    collapse2text: 'Titre bloc 2',
    collapse3img: 'Image bloc 3',
    collapse3text: 'Titre bloc 3',
    collapse4img: 'Image bloc 4',
    collapse4text: 'Titre bloc 4',
    collapse5img: 'Image bloc 5',
    collapse5text: 'Titre bloc 5',
    carouselTitle: 'Titre Gallery ',
    carouselText: 'Description Gallery',
    carousel1img: 'Image 1 Gallery',
    carousel2img: 'Image 2 Gallery',
    carousel3img: 'Image 3 Gallery',
    carousel4img: 'Image 4 Gallery',
    carousel5img: 'Image 5 Gallery',
    carousel6img: 'Image 6 Gallery',
    carousel7img: 'Image 7 Gallery',
    carousel7alt: 'Image 9 Gallery',
    cardsTitle: 'Titre Card',
    cardsIntro: 'Description Card',
    card1title: 'Card 1 Titre',
    card1text: 'Card 1 Description',
    card2title: 'Card 2 Titre',
    card2text: 'Card 2 Description',
    card3title: 'Card 3 Titre',
    card3text: 'Card 3 Description',
    card4title: 'Card 4 Titre',
    card4text: 'Card 4 Description'
  };
  